- manager.go
- user.go
> Feature/Ernest 1870: Update password for a user

- datacenter.go
- group.go
- manager.go
- manager_datacenter.go
- manager_group.go
- manager_login.go
- manager_service.go
- manager_user.go
- manager_user_test.go
- user.go
This pull request implements the endpoints:
> Groups implementation

- monitor.go
> enabling base64 encoding of sse payload

- monitor.go
Issue details : https://github.com/ernestio/ernest/issues/32
> service monitor command does not work

- monitor.go
> cleaning null characters from input messages

- internal/features/cli/service_info.feature
- service_info_view.go
- service_model.go
> Exposes elb name and dns through the service info command

- service_info_view.go
- service_model.go
> added additional AZ field

- definition.yml
> removed router adapter and builder

- internal/features/cli/service_definition.feature
- service_controller.go
Fixes https://github.com/ernestio/ernest/issues/145
> [#145] : Avoid panics on service definition without args

- service_controller.go
- service_info_view.go
- service_model.go
Fixes : https://github.com/ernestio/ernest/issues/132
> [#ERNEST-132] : Expose last known error to the end user

- service_controller.go
> [FIX] ernest-cli out of bound error

- circle.yml
- datacenter.go
- internal/features/cli/datacenter_create_aws.feature
- internal/features/cli/datacenter_delete.feature
- internal/features/cli/datacenter_update.feature
- internal/features/cli/service_apply.feature
- internal/features/cli/service_definition.feature
- internal/features/cli/service_destroy.feature
- internal/features/cli/service_history.feature
- internal/features/cli/service_info.feature
- internal/features/cli/service_list.feature
- internal/features/cli/service_reset.feature
- internal/features/cli/step_definitions.go
- utils.go
Fixes https://github.com/ernestio/ernest/issues/162
> [#ERNEST-162] : Stronger aws validation rules

- README.md
FIX invalid link to `cli-guide`.
> [FIX] invalid doc link

- Makefile
- docs.go
- main.go
> ernest-cli docs will open ernest.io docs section

- service_controller.go
Added return nil to avoid panic when missing args
> Update service_controller.go - DefinitionService

- manager_service.go
- service_controller.go
- service_history_view.go
- service_info_view.go
Fixes : https://github.com/ernestio/ernest/issues/160
> [#ERNEST-160] : identify builds by its application relative id

- internal/features/cli/service_destroy.feature
- manager_service.go
- service_controller.go
Fixes : https://github.com/ernestio/ernest/issues/171
> [#ERNEST-171] : Diferentiate --force and --yes flags

- command/service.go
Fixes : https://github.com/ernestio/ernest/issues/177
> [#ERNEST-177] : Fix output for non destroyed services

- command/datacenter.go
Fixes : https://github.com/ernestio/ernest/issues/175
> Add alias for datacenter creation flags

- command/command.go
- command/service.go
- command/setup.go
- command/target.go
- internal/features/cli/logger_management.feature
- internal/features/cli/step_definitions.go
- main.go
Fixes : https://github.com/ernestio/ernest/issues/157
> [#ERNEST-157] : Ernest setup command

- model/service.go
- view/service_info.go
Fixes : https://github.com/ernestio/ernest/issues/179
> [#ERNEST-179] : Expose rds endpoints

- model/service.go
- view/service_info.go
> [#ERNEST-216] : Expose EBS on GET /service/:service

- README.md
Fixes : https://github.com/ernestio/ernest/issues/214 and https://github.com/ernestio/ernest-cli/issues/50
> Fix readme inconsistencies

- command/component.go
Fixes https://github.com/ernestio/ernest/issues/248
> Fix component list inline docs

- Makefile
- command/log.go
- command/monitor.go
- helper/monitor.go
- main.go
- manager/service.go
- model/logger.go
- model/message.go
Allows CLI tool to inline print the logs [more info here](https://github.com/ernestio/ernest/pull/298)
> 'ernest-cli log' command

- command/usage.go
- internal/features/cli/usage_report.feature
- main.go
- manager/usage.go
- report.log
Implements https://github.com/ernestio/ernest/issues/297
> Command ernest usage added

- manager/service.go
> Corrected typo

- command/docs.go
Implements : https://github.com/ernestio/ernest/issues/304
> Updated docs url

- command/login.go
- model/service.go
- view/service_info.go
implements ernestio/ernest#288
> Windows login & fix vpc output

- command/service.go
- manager/service.go
implements ernestio/ernest#286
> adding filters argument to import

- .ernest-ci
- manager/service.go
> Fix destroy behaviour on in_progress services

- command/service.go
- manager/service.go
> Add feature for service revert

- command/command.go
- command/monitor.go
- helper/build_handler.go
- helper/log_handler.go
- helper/monitor.go
- helper/raw_handler.go
- helper/render.go
- manager/manager.go
- manager/service.go
Fixes need for sleep on writing live output
Cleaned up process of connecting to stream (happens now after api calls, rather than before)
> cleaning up stream id + other fixes

- command/aws_datacenter.go
- command/azure_datacenter.go
- command/group.go
- command/service.go
- command/setup.go
- command/user.go
- command/vcloud_datacenter.go
- helper/monitor.go
- manager/manager.go
- manager/service.go
- manager/user.go
- view/components_list.go
Fixes : https://github.com/ernestio/ernest/issues/411
> [#ERNEST-411] : Remove unused code

- manager/env.go
- model/definition.go
[Green build](https://circleci.com/gh/ernestio/api-gateway/712)
> Restructure REST endpoints

- command/user.go
- model/user.go
Fixes : https://github.com/ernestio/ernest/issues/662
> [#ERNEST-662] : Show user type in `ernest user list`

- command/user.go
- view/user_info.go
- view/user_list.go
> [#ERNEST-763] : Get rid of group column on user listing

- command/monitor.go
Fixes : https://github.com/ernestio/ernest/issues/793
> [#ERNEST-739] : Monitor not working on fresh build of Ernest

- command/schedule.go
Fixes https://github.com/ernestio/ernest/issues/830
> [#ERNEST-830] Fix problem on duplicate flags for envs schedule add

- .linter.conf
- Makefile
- command/env.go
Fixes : https://github.com/ernestio/ernest/issues/837
Fixes : https://github.com/ernestio/ernest/issues/838
> [#ERNEST-837] : Fix import not working pre-release bug

- Gopkg.lock
- Gopkg.toml
- command/command.go
- helper/error.go
- icommand/console.go
- icommand/defaults.go
- icommand/env.go
- icommand/exit.go
- icommand/info.go
- icommand/login.go
- icommand/notification.go
- icommand/policy.go
- icommand/project.go
- icommand/role.go
- icommand/schedule.go
- icommand/sudo.go
- icommand/whoami.go
- main.go
command/roles.go
command/monitor.go
command/log.go
command/env.go
command/policy.go
command/logout.go
command/user.go
command/notification.go
command/preferences.go
command/target.go
command/azure_project.go
command/vcloud_project.go
command/aws_project.go
command/docs.go
command/project.go
command/usage.go
command/info.go
command/login.go
command/schedule.go
> [WIP] Interactive cli PoP
